from pykson import BooleanField, DateField, IntegerField, JsonObject, ObjectField, StringField

class Setting(JsonObject):

	draft_type = StringField()
	is_auction_draft = StringField()
	scoring_type = StringField()
	uses_playoff = StringField()
	has_playoff_consolation_games = BooleanField()
	playoff_start_week = StringField()
	uses_playoff_reseeding = IntegerField()
	uses_lock_eliminated_teams = IntegerField()
	num_playoff_teams = StringField()
	num_playoff_consolation_teams = IntegerField()
	has_multiweek_championship = IntegerField()
	waiver_type = IntegerField()
	uses_faab = StringField()
	post_draft_players = StringField()
	max_teams = StringField()
	waiver_time = StringField()
	trade_end_date = DateField()
	trade_ratify_type = StringField()
	trade_reject_time = StringField()
	cant_cut_list = StringField()
	roster_positions = ObjectListField(RosterPosition)
	stat_categories = StatCategories()
	stat_modifiers = StatModifiers()
	divisions = ObjectListField(Division)
	pickem_enabled = StringField()
	uses_fractional_points = StringField()
	uses_negative_points = StringField()